config/routes.rb
# Rails.application.routes.draw do
#   get 'books/top'
#   get 'books/new'
#   get 'books/index'
#   get 'books/show'
#   get 'books/edit'
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# end
Rails.application.routes.draw do
# get 'books' => 'books#index'
#   post 'books' => 'books#create'
#   get 'books/:id' => 'books#show', as: 'book'
#   get 'books/:id/edit' => 'books#edit', as: 'edit_book'
#   patch 'books/:id' => 'books#update', as: 'update_book'
#   put 'books/:id' => 'books#update'
#   delete 'books/:id' => 'books#destroy', as: 'destroy_book'
root :to => 'books#top'
  patch 'books/:id' => 'books#update', as: 'update_book'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to  books_path, notice: "Book was successfully deleted."
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book,url: update_book_path(@book.id),method: :patch do |f| %>
  <% if @book.errors.any? %>
  <div id="error_explanation">
  <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  </div>
  <div class="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label for="book_body">Body</label>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Update Book' %>
  </div>
<% end %>
<tr>
  <td><%= link_to "Show", book_path(@book.id) %></td>
  <td>|</td>
  <td><%= link_to "Back", books_path %></td>
</tr>

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1>Books</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

<h2>New Book</h2>

<%= form_with model: @book, url:'/books', method: :post do |f| %>
<input name="utf8" type="hidden" value="✓">
 <% if @book.errors.any? %>
 <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>
  </div>
  <div class="field">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
  </div>
  <div class="field">
      <label for="book_body">Body</label>
      <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Book' %>
  </div>

<% end %>

app/views/books/new.html.erb
<p id="notice"><%= flash[:notice] %></p>
  <p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<tr>
  <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
  <td>|</td>
  <td><%= link_to "Back", books_path %></td>
</tr>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
  <p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<tr>
  <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
  <td>|</td>
  <td><%= link_to "Back", books_path %></td>
</tr>

app/views/books/top.html.erb
<h1>
  ようこそ <strong>Bookers</strong> へ！
</h1>

<p>
  <strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
</p>

<p>印象を共有し交換することができます</p>
<p>
  <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>